CREATE TABLE LOCALISATION(
	ID INT PRIMARY KEY,
	LABEL VARCHAR(120)
);

CREATE TABLE SCHOOL (
	ID INT PRIMARY KEY,
	NAME VARCHAR(120),
	IMAGE BLOB,
	LINK VARCHAR(120),
	LOCALISATION_ID INT,
	CONSTRAINT FOREIGN KEY (LOCALISATION_ID) REFERENCES LOCALISATION(ID)
);

CREATE TABLE EDUCATION (
	ID INT PRIMARY KEY,
	NAME VARCHAR(120),
	FIELD VARCHAR(120),
	START_DATE VARCHAR(4),
	END_DATE VARCHAR(4),
	SCHOOL_ID INT,
	CONSTRAINT FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(ID)
);

CREATE TABLE EXPERIENCE (
	ID INT PRIMARY KEY,
	COMPANY VARCHAR(120),
	IMAGE BLOB,
	DURATION VARCHAR(20),
	LOCALISATION_ID INT,
	START_DATE VARCHAR(4),
	END_DATE VARCHAR(4),
	LABEL VARCHAR(120),
	CONSTRAINT FOREIGN KEY (LOCALISATION_ID) REFERENCES LOCALISATION(ID)
);

CREATE TABLE TASK_LIST (
	ID INT PRIMARY KEY,
	LABEL VARCHAR(120),
	EXPERIENCE_ID INT
);

CREATE TABLE LANGUAGES (
	LABEL VARCHAR(120) PRIMARY KEY,
	LEVEL VARCHAR(50),
	COMMENT VARCHAR(120)
);

CREATE TABLE DIVERSE_SECTIONS (
	ID INT PRIMARY KEY,
	TITLE VARCHAR(50),
	SUBTITLE VARCHAR(50),
	COMMENT VARCHAR(250)
);

CREATE TABLE PROGRAMMING (
	NAME VARCHAR(50) PRIMARY KEY,
	LEVEL INT,
	COMMENT VARCHAR(120)
);
